name: build_docs
on: 
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Build
        uses: ammaraskar/sphinx-action@0.4
      - name: Commit
        run: |
          # clone
          git clone --single-branch https://github.com/jgcodes2020/pancake.git -b gh-pages gh-pages
          rsync -a --delete docs/_build/html/ gh-pages --exclude .git
          # setup extra files
          cd gh-pages
          cat > README.md <<EOF
          # Pancake's docs on GitHub Pages
          Well, look what you've found! These generated docs are maintained by GitHub Actions.
          If you're looking to contribute to these docs, go to the `docs` folder on the `master` branch.
          
          Thanks!
          EOF
          cat > .nojekyll <<EOF
          Whatchu know 'bout rolling down in the deep?
          When your brain goes numb, you can call that mental freeze
          When these people talk too much, put that crap in slow motion
          Yeah, I feel like an astronaut in the ocean
          EOF
          
          # commit
          git config user.email action@github.com
          git config user.name "GitHub Actions"
          git add .
          git commit -m "Update docs: `date +"%D at %r"`" -a || true
        shell: bash
      - name: Push to GitHub
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: gh-pages
          branch: gh-pages
          force: true